### ISSUE TITLE
New home of the repository?

### ISSUE THREAD

**Issue by snth** [JanKaul/iceberg-rust#10]
I see that the repo name has changed to **iceberg-rust_archive** and I saw a tweet about the following new repo https://github.com/apache/iceberg-rust .

@JanKaul given that you are a contributor on that repo, is it safe to say that it's been migrated to there?

Perhaps you can just put a note and a link to the new repo in the README to direct anyone that stumbles onto this.

Thanks

**Comment by JanKaul** [comment]
Sorry for not writing a notice. Last week we combined the efforts to create an official Apache repo for the rust implementation. You can expect the new repo to have similar functionality soon.
