### ISSUE TITLE
Status of Writing to Iceberg?

### ISSUE THREAD

**Issue by jacksonrnewhouse** [JanKaul/iceberg-rust#2]
Hi there, I'm building something that uses datafusion for parts of the planning and would like to be able to write results directly to Iceberg. Is the intent of this project to support that eventually? How much effort would it take and could I potentially help with that?

**Comment by JanKaul** [comment]
Hi, it's definitely planned to support writing to iceberg. I just didn't get around to implementing it.
And I haven't figured out a perfect way to do so. I think Datafusion currently doesn't have the functionality for INSERT INTO operations. So the current solution probably requires some external writer.
We can have a look at how delta_rs is doing it.

**Comment by jacksonrnewhouse** [comment]
I'm currently only using the parsing and planning components of DataFusion and performing the execution separately. Since 17.0 the DataFusion grammar now supports WriteOps, via this PR: https://github.com/apache/arrow-datafusion/pull/4902

**Comment by JanKaul** [comment]
Okay great, I will have a look. If you have an idea how this could be implemented it would be great if you could share it here. I will also report my findings.

**Comment by doki23** [comment]
Do we have rust api for writing?

**Comment by JanKaul** [comment]
No, not yet. But I will look into it in the coming days.

**Comment by JanKaul** [comment]
It's been a while but the crate now supports writing to iceberg tables with datafusion.
