### ISSUE TITLE
timestamp with timezone primitive type should be timestamptz

### ISSUE THREAD

**Issue by qinix** [JanKaul/iceberg-rust#25]
current timestamp with timezone type is named `timestampz`, however which should be `timestamptz` per the spec.

https://github.com/JanKaul/iceberg-rust/blob/200118bb87d5ba9896234323dc7da54a0946beb6/iceberg-rust-spec/src/spec/types.rs#L70

https://iceberg.apache.org/spec/#primitive-types

**Comment by JanKaul** [comment]
Thanks for bringing this up, I will fix it in the next days.
