### ISSUE TITLE
`README` mixes up `order_id` with `product_id`

### ISSUE THREAD

**Issue by ahirner** [JanKaul/iceberg-rust#26]
`batches` select `product_id` and all their amouts:

https://github.com/JanKaul/iceberg-rust/blob/200118bb87d5ba9896234323dc7da54a0946beb6/README.md?plain=1#L159-L160

Iterating over this column with a variable named `order_id`:

https://github.com/JanKaul/iceberg-rust/blob/200118bb87d5ba9896234323dc7da54a0946beb6/README.md?plain=1#L169-L174

Furthermore, `asserts`  on `order_id`:

https://github.com/JanKaul/iceberg-rust/blob/200118bb87d5ba9896234323dc7da54a0946beb6/README.md?plain=1#L181-L183

This is semantically correct, but variable should be named `product_id` in the both assertion loops.

**Comment by JanKaul** [comment]
Thanks for reporting this, I'll try to fix it as soon as possible.

**Comment by JanKaul** [comment]
I fixed the issue, thanks for reporting!
