### ISSUE TITLE
Please summarize relationship to another Rust implementation

### ISSUE THREAD

**Issue by shanesveller** [JanKaul/iceberg-rust#33]
Thank you for your work in this repository and elsewhere. For clarity reasons, could you please summarize somewhere on the repo how (in your own view) this project relates to http://github.com/apache/iceberg-rust ? I see that you have contributed regularly there as well, so understanding how and where you choose to work on each repository could be illuminating. Some example questions I have are below, but whatever level of detail and format you feel is appropriate would be very welcome.

- Do you foresee yourself proposing code or designs from this repository for use in the one in the Apache org?
- Do you foresee this repository being long-lived in parallel to that one?
- Do you foresee this repository ever deliberately having non-overlapping features or differing trade-offs from that one?
- Do you hope to tailor this repository for any specific use-cases or peer crate dependencies?

**Comment by JanKaul** [comment]
Hi there, I was involved in the creation of the [https://github.com/apache/iceberg-rust](https://github.com/apache/iceberg-rust) repo and made early contributions. Lately I focused again on this repo as I don't have the time to reimplement the functionality of this library in the official one. 

Let me try to answer your questions:

- Do you foresee yourself proposing code or designs from this repository for use in the one in the Apache org?
As the official repo uses a different approach for the library it is difficult to apply designs from this repo to the official one. However, I see myself proposing code if it fits.

- Do you foresee this repository being long-lived in parallel to that one?
When the official repo reaches feature parity with this repo, I see myself switching to the official repo. Until then I will continue to use this repo. But generally you can expect much better support from the official repo as it has many more maintainers.

- Do you foresee this repository ever deliberately having non-overlapping features or differing trade-offs from that one?
One reason why I continued developing this repo is it's focus on Datafusion and the use of the arrow ecosystem. By focusing on one consumer, it's possible to provide a tighter and lighter integration. You could see that as a trade-off.

- Do you hope to tailor this repository for any specific use-cases or peer crate dependencies?
Similar to the previous question. The focus lies on the integration with datafusion.

**Comment by shanesveller** [comment]
Very clear, thank you!
