### ISSUE TITLE
Inconsistent unit test

### ISSUE THREAD

**Issue by ZENOTME** [JanKaul/iceberg-rust#6]
After https://github.com/JanKaul/iceberg-rust/commit/ccbfae6519e7e3cd3f732f00df653b21aaf8aa08, the append api in transcation become `pub fn append(mut self, files: Vec<(String, FileMetaData)>)`.

Some unit test seems not modify accroding it. https://github.com/JanKaul/iceberg-rust/blob/0ed2ff0f7bf6e988bd500f6186a603a6a0e12e3b/iceberg-rust/src/table/files.rs#L152

https://github.com/JanKaul/iceberg-rust/blob/0ed2ff0f7bf6e988bd500f6186a603a6a0e12e3b/iceberg-rust/src/table/transaction/operation.rs#L848

**Comment by JanKaul** [comment]
Thanks for the heads up. I'm working on a new unit test right now. I will report here once I'm finished. Sorry for pushing this to main, I should have finished this on a separate branch.

**Comment by JanKaul** [comment]
The unit tests should be fixed now. Again, thanks for the heads up.

**Comment by ZENOTME** [comment]
Thanks to fix it!
